[package]
name = "echo_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinymux = {path = "../tinymux" }
#hdrhistogram = "6.0.0"

