[package]
name = "tiny-ws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinymux = {path = "../tinymux" }
rustls = "0.20.6"
webpki-roots = "0.22.3"

